Repository codestates-seb/seb41_main_024, pull requests merged in 2023-01, with the labels that each got.

#3 feat - #2 : 1차 배포 작업 완료
  .idea/misc.xml
  .idea/workspace.xml
  server/.gitignore
  server/README.md
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/main024/ngether/NgetherApplication.java
  server/src/main/java/com/main024/ngether/auth/dto/LoginDto.java
  server/src/main/java/com/main024/ngether/auth/dto/LoginResponseDto.java
  server/src/main/java/com/main024/ngether/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/main024/ngether/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/main024/ngether/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/main024/ngether/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/main024/ngether/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/main024/ngether/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/main024/ngether/auth/utils/MemberDetailsService.java
  server/src/main/java/com/main024/ngether/board/Board.java
  server/src/main/java/com/main024/ngether/board/BoardController.java
  server/src/main/java/com/main024/ngether/board/BoardDto.java
  server/src/main/java/com/main024/ngether/board/BoardMapper.java
  server/src/main/java/com/main024/ngether/board/BoardRepository.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
  server/src/main/java/com/main024/ngether/config/WebConfig.java
  server/src/main/java/com/main024/ngether/dto/ErrorResponse.java
  server/src/main/java/com/main024/ngether/exception/BusinessLogicException.java
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
  server/src/main/java/com/main024/ngether/exception/GlobalExceptionAdvice.java
  server/src/main/java/com/main024/ngether/helper/event/MemberRegistrationApplicationEvent.java
  server/src/main/java/com/main024/ngether/likes/Like.java
  server/src/main/java/com/main024/ngether/likes/LikeRepository.java
  server/src/main/java/com/main024/ngether/likes/LikeService.java
  server/src/main/java/com/main024/ngether/member/Member.java
  server/src/main/java/com/main024/ngether/member/MemberController.java
  server/src/main/java/com/main024/ngether/member/MemberDto.java
  server/src/main/java/com/main024/ngether/member/MemberMapper.java
  server/src/main/java/com/main024/ngether/member/MemberRepository.java
  server/src/main/java/com/main024/ngether/member/MemberService.java
  server/src/main/resources/application.yml
  server/src/test/java/com/main024/ngether/NgetherApplicationTests.java
Labels: back

#5 Feat/back/setting
  .idea/jpa-buddy.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  server/src/main/java/com/main024/ngether/auth/dto/LoginResponseDto.java
  server/src/main/java/com/main024/ngether/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/main024/ngether/board/Board.java
  server/src/main/java/com/main024/ngether/board/BoardController.java
  server/src/main/java/com/main024/ngether/board/BoardDto.java
  server/src/main/java/com/main024/ngether/board/BoardMapper.java
  server/src/main/java/com/main024/ngether/board/BoardRepository.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
  server/src/main/java/com/main024/ngether/likes/LikeRepository.java
  server/src/main/java/com/main024/ngether/member/Member.java
  server/src/main/java/com/main024/ngether/member/MemberDto.java
  server/src/main/java/com/main024/ngether/member/MemberService.java
  server/src/main/resources/application.yml
Labels: back

#6 feat - #2 : 1차 배포 빌드 완료
  server/src/main/resources/application.yml
  server/src/test/java/com/main024/ngether/NgetherApplicationTests.java
Labels: back

#11 feat - #10 : member dto 유효성 검사 완료
  server/src/main/java/com/main024/ngether/exception/GlobalExceptionAdvice.java
  server/src/main/java/com/main024/ngether/member/MemberController.java
  server/src/main/java/com/main024/ngether/member/MemberDto.java
Labels: back

#20 Feat/front/input
  client/components/atoms/input/Input.tsx
  client/components/atoms/input/Type_input.ts
  client/components/atoms/label/Label.tsx
  client/components/atoms/label/Type_label.ts
Labels: front

#23 Feat/front/input
  .github/auto_assign.yml
  client/.storybook/main.js
  client/.storybook/preview.js
  client/components/atoms/input/Input.tsx
  client/components/atoms/input/Type_input.ts
  client/components/atoms/label/Label.tsx
  client/components/atoms/label/Type_label.ts
  client/components/atoms/passwordIcon/PasswordIcon.tsx
  client/components/atoms/passwordIcon/Type_passwordIcon.ts
  client/components/molecules/dropdownInput/DropdownInput.stories.tsx
  client/components/molecules/dropdownInput/DropdownInput.tsx
  client/components/molecules/passwordTextField/TextField.stories.tsx
  client/components/molecules/passwordTextField/TextField.tsx
  client/package.json
  client/stories/Button.stories.tsx
  client/stories/Button.tsx
  client/stories/Header.stories.tsx
  client/stories/Header.tsx
  client/stories/Introduction.stories.mdx
  client/stories/Page.stories.tsx
  client/stories/Page.tsx
  client/stories/assets/code-brackets.svg
  client/stories/assets/colors.svg
  client/stories/assets/comments.svg
  client/stories/assets/direction.svg
  client/stories/assets/flow.svg
  client/stories/assets/plugin.svg
  client/stories/assets/repo.svg
  client/stories/assets/stackalt.svg
  client/stories/button.css
  client/stories/header.css
  client/stories/page.css
  client/yarn.lock
Labels: front

#27 fix - next.config.js 에러 수정
  client/next.config.js
Labels: front

#37 Feat/front/font ntkr
  client/.storybook/main.js
  client/next.config.js
  client/pages/_app.tsx
  client/pages/index.tsx
  client/public/fonts/NotoSans-Black.otf
  client/public/fonts/NotoSans-Black.woff
  client/public/fonts/NotoSans-Black.woff2
  client/public/fonts/NotoSans-Bold.otf
  client/public/fonts/NotoSans-Bold.woff
  client/public/fonts/NotoSans-Bold.woff2
  client/public/fonts/NotoSans-DemiLight.otf
  client/public/fonts/NotoSans-DemiLight.woff
  client/public/fonts/NotoSans-DemiLight.woff2
  client/public/fonts/NotoSans-Light.otf
  client/public/fonts/NotoSans-Light.woff
  client/public/fonts/NotoSans-Light.woff2
  client/public/fonts/NotoSans-Medium.otf
  client/public/fonts/NotoSans-Medium.woff
  client/public/fonts/NotoSans-Medium.woff2
  client/public/fonts/NotoSans-Regular.otf
  client/public/fonts/NotoSans-Regular.woff
  client/public/fonts/NotoSans-Regular.woff2
  client/public/fonts/NotoSans-Thin.otf
  client/public/fonts/NotoSans-Thin.woff
  client/public/fonts/NotoSans-Thin.woff2
  client/public/fonts/fonts.d.ts
  client/styles/globals.css
  client/theme/basic.ts
Labels: front

#38 feat - #29 UI 구현
  client/components/molecules/drawerListItem/DrawerListItem.stories.tsx
  client/components/molecules/drawerListItem/DrawerListItem.tsx
  client/components/molecules/drawerListItem/Type_drawerListItem.ts
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/components/organisms/headers/drawer/DrawerList.tsx
  client/components/organisms/headers/drawer/Type_drawer.ts
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/public/header/arrowback.svg
  client/public/header/arrowbackRight.svg
  client/public/header/menu.svg
  client/public/header/navigator.svg
  client/public/header/search.svg
  client/public/logos/logoBig.svg
  client/public/logos/logoCol.svg
  client/public/logos/logoFooter.svg
  client/public/logos/logoNoContent.svg
  client/public/logos/logoRow.svg
Labels: front

#39 Feat/front/navbar UI
  client/components/atoms/badge/Badge.tsx
  client/components/molecules/navbarBtn/NavbarBtn.tsx
  client/components/molecules/navbarBtn/Type_navbarBtn.ts
  client/components/molecules/spot/Spot.tsx
  client/components/organisms/chatItem/ChatItem.tsx
  client/components/organisms/navbar/Navbar.tsx
  client/components/organisms/navbar/Type_navbar.ts
  client/pages/navbar/index.tsx
  client/public/favicon.ico
  client/public/navbar/ChatIcon.tsx
  client/public/navbar/HomeIcon.tsx
  client/public/navbar/MapIcon.tsx
  client/public/navbar/MypageIcon.tsx
  client/public/navbar/NewIcon.tsx
  client/public/next.svg
  client/public/thirteen.svg
  client/public/vercel.svg
  client/src/assets/navbar/chat.svg
  client/src/assets/navbar/home.svg
  client/src/assets/navbar/map.svg
  client/src/assets/navbar/mypage.svg
  client/src/assets/navbar/new.svg
  client/src/assets/pepsi.svg
  client/tsconfig.json
Labels: front

#46 chore : next.js에서 base64만 내보내는 Webpack 로더 svg 설정 수정
  client/next.config.js
Labels: front

#47 fix : src/assets 경로 관련 항목 삭제, storybook 적적 폴더 속성 수정
  client/.storybook/main.js
  client/components/molecules/navbarBtn/NavbarBtn.stories.tsx
  client/src/custom.d.ts
  client/tsconfig.json
Labels: bug, front

#49 Feat/front/sub footer
  client/components/molecules/footer/Footer.tsx
  client/components/molecules/footer/footer.module.css
  client/components/molecules/footer/footer.stories.tsx
  client/pages/hj/index.tsx
Labels: front

#52 Feat/front/slogan
  client/components/molecules/slogan/Slogan.tsx
  client/components/molecules/slogan/slogan.module.css
  client/components/molecules/slogan/slogan.stories.tsx
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
Labels: front

#59 Feat/front/mypage
  client/components/atoms/formbutton/FormButton.tsx
  client/components/atoms/formbutton/Type_formbutton.ts
  client/components/atoms/input/Input.tsx
  client/components/atoms/input/Type_input.ts
  client/components/atoms/label/Label.tsx
  client/components/molecules/contentTextField/ContentTextField.tsx
  client/components/molecules/passwordTextField/TextField.tsx
  client/components/molecules/passwordTextField/Type_passwordTextField.ts
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/questionForm/QuestionForm.tsx
  client/components/organisms/questionList/QuestionList.tsx
  client/components/organisms/questionListItem/QuestionListItem.tsx
  client/components/organisms/tab/myPageTab/MyPageTab.tsx
  client/components/organisms/tabPanel/myPage/UserInfoEdit.tsx
  client/components/organisms/tabPanel/myPage/UserInquiry.tsx
  client/pages/mypage/[userId].tsx
  client/public/imageBox/base-box.svg
  client/public/imageBox/upload-box.svg
Labels: front

#58 Feat/front/MainPage
  client/components/atoms/alert/Alert.tsx
  client/components/atoms/icons/icons.tsx
  client/components/organisms/bottomNav/bottomNav.tsx
  client/components/organisms/chatItem/ChatItem.tsx
  client/components/organisms/chatItem/ChatItemWithAlert.tsx
  client/pages/main/index.tsx
Labels: front

#60 Feat/front/around
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/sharingListItem/Type_ListItem.ts
  client/components/molecules/sharingListItem/sharingListItem.module.css
  client/components/organisms/nearByList/NearByList.tsx
  client/components/organisms/tab/nearByPageTab/NearByPageTab.tsx
  client/pages/hj/index.tsx
  client/pages/nearby/index.tsx
  client/public/sharingList/map.svg
Labels: front

#61 Feat/front/mypage
  client/components/molecules/userInfoForm/Type_UserInfoForm.ts
  client/components/molecules/userInfoForm/UserInfoForm.tsx
  client/components/organisms/tabPanel/myPage/UserInfoEdit.tsx
Labels: front

#65 Feat/front/refactoring
  client/components/atoms/button/Button.tsx
  client/components/atoms/button/Type_Button.ts
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/sharingListItem/sharingListItem.module.css
  client/public/sharingList/favorite.svg
Labels: front

#67 feat - #66 search UI 구현
  client/components/molecules/noContent/NoContent.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/questionForm/QuestionForm.tsx
  client/components/organisms/questionList/QuestionList.tsx
  client/pages/search/index.tsx
  client/public/logos/logoNoContent.svg
Labels: front

#69 Feat/front/refactoring
  client/components/atoms/formbutton/FormButton.tsx
  client/components/atoms/input/Input.tsx
  client/components/atoms/label/Label.tsx
  client/components/atoms/passwordIcon/PasswordIcon.tsx
  client/components/atoms/tab/TabPanel.tsx
  client/components/molecules/contentTextField/ContentTextField.tsx
  client/components/molecules/drawerListItem/DrawerListItem.tsx
  client/components/molecules/footer/Footer.tsx
  client/components/molecules/noContent/NoContent.tsx
  client/components/molecules/slogan/Slogan.tsx
  client/pages/index.tsx
  client/pages/mypage/[userId].tsx
  client/pages/search/index.tsx
Labels: front

#70 refactor : 이미지 태그 {ReactComponent as ~} 변환 및 Quote 수정
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/components/organisms/headers/drawer/DrawerList.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/questionForm/QuestionForm.tsx
  client/components/organisms/questionList/QuestionList.tsx
  client/components/organisms/questionListItem/QuestionListItem.tsx
Labels: front

#73 Feat/front/detailpage
  client/components/molecules/detailBottom/DetailBottom.tsx
  client/components/molecules/postMeta/PostMeta.tsx
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/tab/BasicTabs.tsx
  client/components/molecules/tab/Type_BasicTabs.ts
  client/components/molecules/userMetaInfo/UserMetaInfo.tsx
  client/components/organisms/navbar/Navbar.tsx
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/components/organisms/tab/myPageTab/MyPageTab.tsx
  client/pages/nearbydetail/index.tsx
  client/public/detail/alert.svg
  client/public/detail/edit.svg
  client/public/detail/map.svg
  client/public/detail/straw.svg
  client/tailwind.config.js
Labels: front

#76 Feat/front/addNewPage
  client/components/organisms/bottomNav/bottomNav.tsx
  client/pages/addnew/index.tsx
  client/pages/chatlist/index.tsx
  client/pages/login/index.tsx
Labels: front

#84 feat/front/refactoring : atoms 폴더 컨벤션에 맞게 수정
  client/components/atoms/button/Button.stories.tsx
  client/components/atoms/button/Button.tsx
  client/components/atoms/button/button.ts
  client/components/atoms/formbutton/FormButton.tsx
  client/components/atoms/formbutton/Type_formbutton.ts
  client/components/atoms/formbutton/formButton.ts
  client/components/atoms/image/Image.tsx
  client/components/atoms/image/image.ts
  client/components/atoms/input/Input.tsx
  client/components/atoms/input/input.ts
  client/components/atoms/label/Label.tsx
  client/components/atoms/label/label.ts
  client/components/atoms/passwordIcon/PasswordIcon.tsx
  client/components/atoms/passwordIcon/passwordIcon.ts
  client/components/atoms/tab/TabPanel.tsx
  client/components/atoms/tab/Type_TabPanel.ts
  client/components/atoms/tabPanel/TabPanel.tsx
  client/components/atoms/tabPanel/tabPanel.ts
Labels: front

#83 Feat/front/navbar_refactor : navbar 폴더 삭제
  client/components/organisms/navbar/Navbar.tsx
Labels: front

#93 Feat/front/detach_ts_files : 컴포넌트 ts 파일 분리
  client/components/atoms/alert/Alert.tsx
  client/components/atoms/alert/alert.ts
  client/components/atoms/badge/Badge.tsx
  client/components/atoms/badge/badge.ts
  client/components/molecules/spot/SmallSpot.tsx
  client/components/molecules/spot/Spot.tsx
  client/components/molecules/spot/spot.ts
  client/components/organisms/bottomNav/bottomNav.tsx
  client/components/organisms/chatItem/ChatItem.tsx
  client/components/organisms/chatItem/ChatItemWithAlert.tsx
  client/components/organisms/chatItem/chatItem.ts
Labels: front

#97 Feat/front/imgfileupload - 이미지 업로드 컴포넌트
  client/components/organisms/imgUpLoad/ImgUpload.tsx
  client/components/organisms/imgUpLoad/Type_ImgUpload.ts
  client/components/organisms/imgUpLoad/imgUpLoad.stories.tsx
  client/package.json
  client/public/profile/@thumb252×310.jpg
  client/yarn.lock
Labels: front

#100 Feat/front/pagelayout - 너비설정, layout 컴포넌트 생성
  client/components/atoms/button/Button.tsx
  client/components/atoms/button/button.ts
  client/components/atoms/tabPanel/TabPanel.tsx
  client/components/atoms/tabPanel/tabPanel.ts
  client/components/layout/defalutLayout/DefaultLayout.tsx
  client/components/layout/defalutLayout/defaultLayout.ts
  client/components/layout/layoutWithFooter/LayoutWithFooter.tsx
  client/components/molecules/detailBottom/DetailBottom.tsx
  client/components/molecules/elapsedTime/ElapsedTime.tsx
  client/components/molecules/elapsedTime/elapsedTime.ts
  client/components/molecules/footer/Footer.tsx
  client/components/molecules/postMeta/PostMeta.tsx
  client/components/molecules/postMeta/postMeta.ts
  client/components/molecules/slogan/mainSlogan/MainSlogan.tsx
  client/components/molecules/tab/BasicTabs.tsx
  client/components/molecules/tab/Type_BasicTabs.ts
  client/components/molecules/userMetaInfo/UserMetaInfo.tsx
  client/components/molecules/userMetaInfo/userMetaInfo.ts
  client/components/organisms/bottomNav/bottomNav.tsx
  client/components/organisms/nearByList/NearByList.tsx
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/components/organisms/tab/detailPageTab/detailPageTab.ts
  client/components/organisms/tab/myPageTab/MyPageTab.tsx
  client/components/organisms/tab/mySharingTab/MySharingTab.tsx
  client/components/organisms/tab/nearByPageTab/NearByPageTab.tsx
  client/pages/_app.tsx
  client/pages/addnew/index.tsx
  client/pages/chatlist/index.tsx
  client/pages/hj/index.tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/main/index.tsx
  client/pages/mypage/index.tsx
  client/pages/nearby/index.tsx
  client/pages/nearbydetail/index.tsx
  client/pages/signup/index.tsx
  client/src/custom.d.ts
Labels: front

#103 Feat/front/pagelayout - bottom Nav bar css 변경
  client/components/layout/layoutWithFooter/LayoutWithFooter.tsx
  client/components/organisms/bottomNav/bottomNav.tsx
Labels: front

#105 Feat/front/test uploadform - Jest 세팅, useHook과 test 예시
  client/__tests__/addNew/addNew.ts
  client/hooks/useInput.ts
  client/jest.config.js
  client/package.json
  client/yarn.lock
Labels: front

#95 Feat/front/chatListRefactor : 채팅 아이템 컴포넌트, 채팅 목록 페이지 등 리팩토링
  client/.gitignore
  client/components/atoms/alert/alert.stories.tsx
  client/components/atoms/badge/badge.stories.tsx
  client/components/organisms/bottomNav/bottomNav.stories.tsx
  client/components/organisms/bottomNav/bottomNav.tsx
  client/components/organisms/chatItem/ChatItem.tsx
  client/components/organisms/chatItem/ChatItemWithAlert.tsx
  client/components/organisms/chatItem/chatItem.module.css
  client/data/data.json
  client/pages/addnew/index.tsx
  client/pages/chatlist/index.tsx
  client/pages/main/index.tsx
  client/pages/signup/index.tsx
  client/public/home.svg
  client/public/navbar/ChatIcon.tsx
  client/public/navbar/HomeIcon.tsx
  client/public/navbar/MapIcon.tsx
  client/public/navbar/MypageIcon.tsx
  client/public/navbar/NewIcon.tsx
Labels: front

#106 refactor: molecules ts파일명, interface 식별자명 통일
  client/components/molecules/drawerListItem/DrawerListItem.tsx
  client/components/molecules/drawerListItem/Type_drawerListItem.ts
  client/components/molecules/drawerListItem/drawerListItemType.ts
  client/components/molecules/elapsedTime/ElapsedTime.tsx
  client/components/molecules/elapsedTime/elapsedTimeType.ts
  client/components/molecules/passwordTextField/passwordTextFieldType.ts
  client/components/molecules/postMeta/PostMeta.tsx
  client/components/molecules/postMeta/postMetaType.ts
  client/components/molecules/sharingListItem/sharingListItemType.ts
  client/components/molecules/tab/basicTabsType.ts
  client/components/molecules/userInfoForm/userInfoFormType.ts
  client/components/molecules/userMetaInfo/UserMetaInfo.tsx
  client/components/molecules/userMetaInfo/userMetaInfoType.ts
Labels: front

#108 refactor: organisms ts파일명, interface 식별자명 통일
  client/components/organisms/chatGroup/ChatGroup.tsx
  client/components/organisms/chatGroup/ChatGroupPropsType.ts
  client/components/organisms/chatGroup/chatGroupType.ts
  client/components/organisms/chatRow/ChatRow.tsx
  client/components/organisms/chatRow/chatRowType.ts
  client/components/organisms/headers/drawer/DrawerList.tsx
  client/components/organisms/headers/drawer/Type_drawer.ts
  client/components/organisms/headers/drawer/drawerType.ts
  client/components/organisms/imgUpLoad/ImgUpload.tsx
  client/components/organisms/imgUpLoad/imgUploadType.ts
  client/pages/chatroom/dataChat.tsx
Labels: front

#107 refactor: atoms ts파일명, interface 식별자명 통일 front
  client/components/atoms/alert/Alert.tsx
  client/components/atoms/alert/alert.ts
  client/components/atoms/alert/alertType.ts
  client/components/atoms/badge/Badge.tsx
  client/components/atoms/badge/badge.ts
  client/components/atoms/badge/badgeType.ts
  client/components/atoms/button/Button.tsx
  client/components/atoms/button/buttonType.ts
  client/components/atoms/formbutton/FormButton.tsx
  client/components/atoms/formbutton/formButtonType.ts
  client/components/atoms/image/Image.tsx
  client/components/atoms/image/image.ts
  client/components/atoms/image/imageType.ts
  client/components/atoms/input/Input.tsx
  client/components/atoms/input/inputType.ts
  client/components/atoms/label/Label.tsx
  client/components/atoms/label/labelType.ts
  client/components/atoms/passwordIcon/PasswordIcon.tsx
  client/components/atoms/passwordIcon/passwordIconType.ts
  client/components/atoms/tabPanel/TabPanel.tsx
  client/components/atoms/tabPanel/tabPanelType.ts
Labels: front

#119 Feat/back/chat - 나의 회원정보 조회 수정
  server/src/main/java/com/main024/ngether/member/MemberController.java
  server/src/main/resources/application.yml
Labels: back

#124 feat/back/chat - CORS 수정
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#125 feat/back/chat - CORS 수정
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
Labels: back

#126 Feat/back/location - type -> range로 수정, 위치 등록시 memberId 요청 x 가능
  server/src/main/java/com/main024/ngether/location/LocationController.java
  server/src/main/java/com/main024/ngether/location/LocationDto.java
  server/src/main/java/com/main024/ngether/location/LocationService.java
Labels: back

#128 Feat/back/location - 위치 정보로 검색하는 기능 구현
  server/src/main/java/com/main024/ngether/board/BoardController.java
  server/src/main/java/com/main024/ngether/board/BoardRepository.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
Labels: back

#129 Feat/back/chat -로그인 시 사용자 지정 위치 ID 반환
  server/src/main/java/com/main024/ngether/auth/dto/LoginResponseDto.java
  server/src/main/java/com/main024/ngether/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
  server/src/main/java/com/main024/ngether/location/LocationDto.java
  server/src/main/java/com/main024/ngether/location/LocationRepository.java
Labels: back

#130 feat/back/chat - Webfig 수정
  server/src/main/java/com/main024/ngether/config/WebConfig.java
Labels: back

#131 feat/back/chat - Webfig 수정
  server/src/main/java/com/main024/ngether/config/CorsConfig.java
  server/src/main/java/com/main024/ngether/config/WebConfig.java
Labels: back

#132 feat/back/chat - Webfig 수정
  server/src/main/java/com/main024/ngether/config/CorsConfig.java
Labels: back

#110 feat: 회원가입 form custom Hook 제작 및 회원가입 기능
  client/components/molecules/detailBottom/DetailBottom.tsx
  client/components/molecules/formbutton/FormButton.tsx
  client/components/molecules/formbutton/formButtonType.ts
  client/components/molecules/passwordTextField/TextField.tsx
  client/components/molecules/userInfoForm/UserInfoForm.tsx
  client/components/molecules/userInfoForm/userInfoFormType.ts
  client/components/organisms/questionForm/QuestionForm.tsx
  client/components/organisms/questionList/QuestionList.tsx
  client/hooks/useForm.ts
  client/hooks/useRegexText.ts
  client/pages/addnew/index.tsx
  client/pages/login/index.tsx
  client/pages/main/index.tsx
  client/pages/signup/index.tsx
Labels: front

#133 feat/back/chat - #64 chatHandler수정
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
  server/src/main/java/com/main024/ngether/config/CorsConfig.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#136 feat/back/chat - fig 수정
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
  server/src/main/java/com/main024/ngether/config/CorsConfig.java
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
Labels: back

#137 feat/back/chat - config 수정
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
Labels: back

#138 feat/back/chat - config 수정
  server/src/main/java/com/main024/ngether/config/WebConfig.java
Labels: back

#139 feat/back/chat - config 수정
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
Labels: back

#140 feat/back/chat - config 수정
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
  server/src/main/java/com/main024/ngether/config/WebConfig.java
  server/src/main/resources/application.yml
Labels: back

#141 feat - #64 채팅 보안 부분 원상복귀
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#114 Feat/front/test uploadform
  client/.gitignore
  client/__tests__/addNew/addNew.js
  client/api/post.ts
  client/components/layout/defalutLayout/DefaultLayout.tsx
  client/components/layout/layoutWithFooter/LayoutWithFooter.tsx
  client/components/molecules/formbutton/FormButton.tsx
  client/components/molecules/formbutton/formButtonType.ts
  client/components/molecules/userInfoForm/UserInfoForm.tsx
  client/components/organisms/bottomNav/BottomNav.tsx
  client/hooks/addNewHooks/useInput.ts
  client/hooks/addNewHooks/useInputType.ts
  client/hooks/useInput.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/addnew/index.tsx
  client/yarn.lock
Labels: front

#122 Feat/front/login - 로그인/로그아웃 기능
  client/components/molecules/passwordTextField/TextField.tsx
  client/components/organisms/headers/drawer/drawerType.ts
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/package.json
  client/pages/_app.tsx
  client/pages/login/index.tsx
  client/pages/nearbydetail/index.tsx
  client/tailwind.config.js
  client/yarn.lock
Labels: front

#143 Feat/back/location - BoardController 조회 기능 페이지네이션, 정렬 구현 / 한글 -> 영어 카테고리 수정
  server/src/main/java/com/main024/ngether/board/Board.java
  server/src/main/java/com/main024/ngether/board/BoardController.java
  server/src/main/java/com/main024/ngether/board/BoardDto.java
  server/src/main/java/com/main024/ngether/board/BoardMapper.java
  server/src/main/java/com/main024/ngether/board/BoardRepository.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/board/response/MultiResponseDto.java
  server/src/main/java/com/main024/ngether/board/response/PageInfo.java
  server/src/main/java/com/main024/ngether/location/DistanceRepository.java
  server/src/main/java/com/main024/ngether/location/LocationController.java
  server/src/main/java/com/main024/ngether/location/LocationService.java
Labels: back

#144 feat/back/chat - 채팅방 입장, 퇴장 메시지 출력 완료
  server/src/main/java/com/main024/ngether/board/Board.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatMessage.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatRoomService.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#146 feat/back/chat- 채팅방 개설자가 채팅방 퇴장시 채팅방, 메시지내역, 게시물 삭제
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatRoom.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
Labels: back

#147 Feat/front/nearby - https 설정 dev 머지
  client/.gitignore
  client/api/location.ts
  client/api/post.ts
  client/components/molecules/dropdownInput/DropdownInput.tsx
  client/components/molecules/dropdownInput/dropDownInputType.ts
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/hooks/common/useDropDown.ts
  client/package.json
  client/pages/_document.tsx
  client/pages/addnew/index.tsx
  client/pages/nearby/index.tsx
  client/pages/search/index.tsx
  client/server.js
  client/yarn.lock
Labels: front

#149 feat/back/chat - 채팅방 퇴장시 수정
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
  server/src/main/java/com/main024/ngether/member/MemberController.java
Labels: back

#148 fix - bug fix
  client/api/location.ts
  client/api/post.ts
  client/components/atoms/alert/Alert.tsx
  client/components/atoms/button/Button.tsx
  client/components/molecules/contentTextField/ContentTextField.stories.tsx
  client/components/molecules/contentTextField/ContentTextField.tsx
  client/components/molecules/detailBottom/DetailBottom.tsx
  client/components/molecules/drawerListItem/DrawerListItem.tsx
  client/components/molecules/dropdownInput/DropdownInput.tsx
  client/components/molecules/formbutton/FormButton.tsx
  client/components/molecules/sharingListItem/ListItem.stories.tsx
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/tab/BasicTabs.tsx
  client/components/organisms/chatGroup/ChatGroup.tsx
  client/components/organisms/chatRow/ChatRow.tsx
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/components/organisms/tabPanel/myPage/UserInfoEdit.tsx
  client/data.json
  client/pages/_app.tsx
  client/pages/chat/index.tsx
  client/pages/chatroom/dataChat.tsx
  client/pages/chatroom/index.tsx
  client/yarn.lock
Labels: front

#152 feat - #64 : 게시물 id와 채팅방 id가 동일하지 않을시 생성안되게 변경
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
Labels: back

#153 feat/back/chat - page관련 requestparam수정
  server/src/main/java/com/main024/ngether/board/BoardController.java
  server/src/main/java/com/main024/ngether/location/LocationController.java
Labels: back

#151 fix - websocket 에러 해결
  client/server.js
Labels: front

#154 Feat/front/chatList - 채팅방 목록
  client/.gitignore
  client/api/location.ts
  client/api/post.ts
  client/components/molecules/dropdownInput/DropdownInput.tsx
  client/components/molecules/dropdownInput/dropDownInputType.ts
  client/components/molecules/spot/SmallSpot.tsx
  client/components/molecules/spot/spot.ts
  client/components/organisms/chatItem/ChatItem.tsx
  client/components/organisms/chatItem/ChatItemWithAlert.tsx
  client/components/organisms/chatItem/chatItem.ts
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/data/data.json
  client/hooks/common/useDropDown.ts
  client/package.json
  client/pages/_document.tsx
  client/pages/addnew/index.tsx
  client/pages/chatlist/index.tsx
  client/pages/edit/[id].tsx
  client/pages/login/index.tsx
  client/pages/nearby/index.tsx
  client/pages/search/index.tsx
  client/server.js
  client/yarn.lock
  server/src/main/java/com/main024/ngether/board/Board.java
  server/src/main/java/com/main024/ngether/board/BoardController.java
  server/src/main/java/com/main024/ngether/board/BoardDto.java
  server/src/main/java/com/main024/ngether/board/BoardMapper.java
  server/src/main/java/com/main024/ngether/board/BoardRepository.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/board/response/MultiResponseDto.java
  server/src/main/java/com/main024/ngether/board/response/PageInfo.java
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatMessage.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatRoom.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatRoomService.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
  server/src/main/java/com/main024/ngether/location/DistanceRepository.java
  server/src/main/java/com/main024/ngether/location/LocationController.java
  server/src/main/java/com/main024/ngether/location/LocationService.java
Labels: front

#156 feat/back/chat - 테스트
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
Labels: back

#157 feat/back/chat - 테스트
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
Labels: back

#159 Feat/back/pagination - 페이지네이션 적용 완료
  server/src/main/java/com/main024/ngether/board/BoardController.java
  server/src/main/java/com/main024/ngether/board/BoardRepository.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
  server/src/main/java/com/main024/ngether/location/DistanceRepository.java
  server/src/main/java/com/main024/ngether/location/LocationController.java
  server/src/main/java/com/main024/ngether/location/LocationService.java
  server/src/main/java/com/main024/ngether/member/MemberController.java
Labels: back

#161 feat/back/chat - 채팅방 입장, 퇴장 로직 변경
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatMessage.java
  server/src/main/java/com/main024/ngether/chat/chatRepository/ChatRoomRepository.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatRoomService.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#162 feat/back/chat - chatController 수정
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
Labels: back

#164 feat/back/chat - 입,퇴장시 멤버 리스트 반환
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
Labels: back

#165 Feat/back/pagination - 페이지네이션 수정
  server/src/main/java/com/main024/ngether/board/BoardController.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
  server/src/main/java/com/main024/ngether/location/LocationController.java
  server/src/main/java/com/main024/ngether/location/LocationService.java
Labels: back

#167 feat/back/chat - 오류 수정
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
Labels: back

#168 feat/back/chat - 오류수정
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
Labels: back

#169 Feat/back/pagination - 내가 등록한 위치 목록들 조회 기능 구현
  server/src/main/java/com/main024/ngether/location/LocationController.java
Labels: back

#174 Feat/back/report - 신고하기 기능, 관리자 페이지 기능
  server/src/main/java/com/main024/ngether/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/main024/ngether/board/Board.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
  server/src/main/java/com/main024/ngether/location/LocationController.java
  server/src/main/java/com/main024/ngether/location/LocationService.java
  server/src/main/java/com/main024/ngether/report/Report.java
  server/src/main/java/com/main024/ngether/report/ReportController.java
  server/src/main/java/com/main024/ngether/report/ReportDto.java
  server/src/main/java/com/main024/ngether/report/ReportMapper.java
  server/src/main/java/com/main024/ngether/report/ReportRepository.java
  server/src/main/java/com/main024/ngether/report/ReportService.java
Labels: back

#175 feat/back/chat - 채팅방 알람 설정 api 추가
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatDto.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatRoom.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
Labels: back

#176 Feat/front/refactoring - 4인 페어프로그래밍 리팩토링
  client/api/detail.ts
  client/api/login.ts
  client/api/post.ts
  client/components/molecules/userMetaInfo/UserMetaInfo.tsx
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/components/organisms/tabPanel/myPage/UserInquiry.tsx
  client/pages/nearby/[id].tsx
  client/yarn.lock
Labels: front

#177 feat - 내가 작성한 게시물인지 체크하는 api 추가
  server/src/main/java/com/main024/ngether/board/BoardController.java
Labels: back

#178 feat/back/kakao - 채팅방 리스트 반환 시 마지막 메시지 저장 시점으로 변경
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatDto.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatRoom.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/member/MemberController.java
Labels: back

#182 feat/back/kakao - 임시로 security수정
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
  server/src/main/java/com/main024/ngether/member/MemberController.java
Labels: back

#184 feat/back/kakao - 정지 당한 유저는 로그인이 안되게 변경, 토큰 발급도 불가
  server/src/main/java/com/main024/ngether/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
  server/src/main/java/com/main024/ngether/report/ReportController.java
  server/src/main/java/com/main024/ngether/report/ReportService.java
Labels: back

#172 Feat/front/cha - 쉐어링 채팅 기능 추가
  client/api/chatSharing.ts
  client/components/container/chatRoomLayout/ChatRoomLayout.tsx
  client/components/container/defalutLayout/DefaultLayout.tsx
  client/components/molecules/chatNoticeRow/ChatNoticeRow.tsx
  client/components/molecules/chatNoticeRow/chatNoticeRow.ts
  client/components/molecules/drawerListItem/DrawerListItem.tsx
  client/components/molecules/drawerListItem/drawerListItemType.ts
  client/components/organisms/chatForm/ChatForm.tsx
  client/components/organisms/chatForm/chatFormType.ts
  client/components/organisms/chatGroup/ChatGroup.tsx
  client/components/organisms/chatItem/ChatItem.tsx
  client/components/organisms/chatRow/ChatRow.tsx
  client/components/organisms/chatRow/chatRowType.ts
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/headers/mainHeader/mainHeader.ts
  client/hooks/useWebSocketClient.ts
  client/package.json
  client/pages/chatroom/[roomId].tsx
  client/pages/chatroom/index.tsx
  client/yarn.lock
Labels: front

#170 Feat/front/uploadpost - 게시물 업로드 지도로 주소 지정하는 기능 추가
  client/api/kakaoMap.ts
  client/api/location.ts
  client/api/post.ts
  client/components/atoms/input/Input.tsx
  client/components/atoms/input/inputType.ts
  client/components/molecules/formbutton/FormButton.tsx
  client/components/molecules/userInfoForm/UserInfoForm.tsx
  client/components/organisms/kakaoMap/KakaoMap.tsx
  client/components/test.tsx
  client/hooks/addNewHooks/useInput.ts
  client/hooks/addNewHooks/useInputType.ts
  client/pages/_document.tsx
  client/pages/addnew/index.tsx
  client/pages/nearby/index.tsx
  client/tsconfig.json
Labels: front

#183 Feat/front/productDetail - 디테일 페이지 UI / fetch 방식 변경
  client/api/detail.ts
  client/api/isWriter.ts
  client/api/login.ts
  client/api/mySharing.ts
  client/components/molecules/userMetaInfo/UserMetaInfo.tsx
  client/components/molecules/userMetaInfo/userMetaInfoType.ts
  client/components/organisms/bottomNav/BottomNav.tsx
  client/components/organisms/detailMap/DetailMap.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/data/data.json
  client/package-lock.json
  client/pages/chatlist/index.tsx
  client/pages/edit/[id].tsx
  client/pages/login/index.tsx
  client/pages/nearby/[id].tsx
Labels: front

#186 refactor - #185 lastMessage 추가
  client/api/detail.ts
  client/api/mySharing.ts
  client/components/atoms/badge/Badge.tsx
  client/components/atoms/badge/badgeType.ts
  client/components/organisms/chatItem/ChatItem.tsx
  client/components/organisms/chatItem/chatItem.ts
  client/pages/chatlist/index.tsx
  client/pages/nearby/[id].tsx
Labels: front

#192 Feat/back/report sub - 유저가 정지 당할 시 처리
  client/api/chatSharing.ts
  client/api/detail.ts
  client/api/login.ts
  client/api/post.ts
  client/components/container/chatRoomLayout/ChatRoomLayout.tsx
  client/components/container/defalutLayout/DefaultLayout.tsx
  client/components/container/defalutLayout/defaultLayout.ts
  client/components/container/layoutWithFooter/LayoutWithFooter.tsx
  client/components/container/loginChecker/LoginChecker.tsx
  client/components/container/loginChecker/loginChecker.ts
  client/components/molecules/chatNoticeRow/ChatNoticeRow.tsx
  client/components/molecules/chatNoticeRow/chatNoticeRow.ts
  client/components/molecules/drawerListItem/DrawerListItem.tsx
  client/components/molecules/drawerListItem/drawerListItemType.ts
  client/components/molecules/userMetaInfo/UserMetaInfo.tsx
  client/components/organisms/chatForm/ChatForm.tsx
  client/components/organisms/chatForm/chatFormType.ts
  client/components/organisms/chatGroup/ChatGroup.tsx
  client/components/organisms/chatItem/ChatItem.tsx
  client/components/organisms/chatRow/ChatRow.tsx
  client/components/organisms/chatRow/chatRowType.ts
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/headers/mainHeader/mainHeader.ts
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/components/organisms/tabPanel/myPage/UserInquiry.tsx
  client/hooks/common/useLogin.ts
  client/hooks/useWebSocketClient.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/addnew/index.tsx
  client/pages/chatroom/[roomId].tsx
  client/pages/chatroom/index.tsx
  client/pages/index.tsx
  client/pages/mypage/index.tsx
  client/pages/nearby/[id].tsx
  client/yarn.lock
  server/src/main/java/com/main024/ngether/auth/dto/LoginResponseDto.java
  server/src/main/java/com/main024/ngether/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/main024/ngether/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/main024/ngether/board/BoardController.java
  server/src/main/java/com/main024/ngether/board/BoardRepository.java
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatDto.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatRoom.java
  server/src/main/java/com/main024/ngether/chat/chatRepository/ChatMessageRepository.java
  server/src/main/java/com/main024/ngether/chat/chatRepository/ChatRoomRepository.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
  server/src/main/java/com/main024/ngether/member/MemberController.java
  server/src/main/java/com/main024/ngether/report/Report.java
  server/src/main/java/com/main024/ngether/report/ReportController.java
  server/src/main/java/com/main024/ngether/report/ReportDto.java
  server/src/main/java/com/main024/ngether/report/ReportMapper.java
  server/src/main/java/com/main024/ngether/report/ReportService.java
Labels: back

#193 Feat/back/report - 관리자 페이지, 신고하기 부분 완료
  server/src/main/java/com/main024/ngether/auth/dto/LoginResponseDto.java
  server/src/main/java/com/main024/ngether/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/main024/ngether/board/BoardRepository.java
  server/src/main/java/com/main024/ngether/chat/chatRepository/ChatMessageRepository.java
  server/src/main/java/com/main024/ngether/chat/chatRepository/ChatRoomRepository.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/report/Report.java
  server/src/main/java/com/main024/ngether/report/ReportController.java
  server/src/main/java/com/main024/ngether/report/ReportDto.java
  server/src/main/java/com/main024/ngether/report/ReportMapper.java
  server/src/main/java/com/main024/ngether/report/ReportService.java
Labels: back

#195 Feat/back/qna - 1대1 문의 게시판
  server/src/main/java/com/main024/ngether/exception/ExceptionCode.java
  server/src/main/java/com/main024/ngether/member/Member.java
  server/src/main/java/com/main024/ngether/qna/qnaController/AnswerController.java
  server/src/main/java/com/main024/ngether/qna/qnaController/QnaController.java
  server/src/main/java/com/main024/ngether/qna/qnaDto/AnswerDto.java
  server/src/main/java/com/main024/ngether/qna/qnaDto/QnaDto.java
  server/src/main/java/com/main024/ngether/qna/qnaEntity/Answer.java
  server/src/main/java/com/main024/ngether/qna/qnaEntity/Qna.java
  server/src/main/java/com/main024/ngether/qna/qnaMapper/AnswerMapper.java
  server/src/main/java/com/main024/ngether/qna/qnaMapper/QnaMapper.java
  server/src/main/java/com/main024/ngether/qna/qnaRepository/AnswerRepository.java
  server/src/main/java/com/main024/ngether/qna/qnaRepository/QnaRepository.java
  server/src/main/java/com/main024/ngether/qna/qnaService/AnswerService.java
  server/src/main/java/com/main024/ngether/qna/qnaService/QnaService.java
Labels: back

#187 Feat/front/og_scrap - 상품링크 받을 시 이미지를 링크의 og데이터의 링크로 동적 변경
  client/package.json
  client/pages/addnew/index.tsx
  client/server.js
  client/yarn.lock
Labels: front

#201 feat/back/chat - 안 읽은 메시지 갯수 표시
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatRoom.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatRoomMembers.java
  server/src/main/java/com/main024/ngether/chat/chatRepository/ChatRoomMembersRepository.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatRoomService.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
  server/src/main/java/com/main024/ngether/qna/qnaController/QnaController.java
Labels: back

#202 feat - #64 읽지 않은 메시지 갯수 표기
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatEntity/ChatDto.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
Labels: back

#203 feat/back/chat - 채팅방 입장 토큰 변화
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#204 feat - #64 채팅방 헤더 수정
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#206 feat/back/chat - 토큰 문제 수정
  server/src/main/java/com/main024/ngether/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#207 feat/back/chat - 토큰 수정
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#208 feat/back/chat - 토큰 수정
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#210 Feat/back/chat - 토큰 수정
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
  server/src/main/java/com/main024/ngether/chat/chatRepository/ChatRoomMembersRepository.java
  server/src/main/java/com/main024/ngether/config/handler/StompHandler.java
Labels: back

#211 feat/back/chat - 메시지 발송 수정
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
Labels: back

#212 feat/back/chat - 메시지 발송 수정
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
Labels: back

#214 feat/back/chat - 좋아요 수정
  server/src/main/java/com/main024/ngether/board/BoardController.java
Labels: back

#215 feat/back/chat - 좋아요 저장시 수정
  server/src/main/java/com/main024/ngether/likes/Like.java
Labels: back

#216 feat/back/chat - 좋아요 상태 수정
  server/src/main/java/com/main024/ngether/likes/Like.java
Labels: back

#217 feat/front/chat - 채팅 리팩토링 및 sever.js 수정
  client/components/organisms/chatGroup/ChatGroup.tsx
  client/components/organisms/chatRow/ChatRow.tsx
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/hooks/useWebSocketClient.ts
  client/pages/addnew/index.tsx
  client/pages/chatroom/[roomId].tsx
  client/server.js
Labels: front

#197 Feat/front/search
  client/api/kakaoMap.ts
  client/api/location.ts
  client/api/post.ts
  client/components/molecules/dropdownInput/DropdownInput.tsx
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/sharingListItem/sharingListItemType.ts
  client/components/organisms/nearByList/NearByList.tsx
  client/components/organisms/tab/nearByPageTab/NearByPageTab.tsx
  client/hooks/addNewHooks/useInput.ts
  client/hooks/addNewHooks/useInputType.ts
  client/hooks/search/useSearch.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/addnew/index.tsx
  client/pages/nearby/index.tsx
  client/pages/search/index.tsx
  client/yarn.lock
Labels: front

#191 Feat/front/refactoring
  client/api/kakaoMap.ts
  client/api/location.ts
  client/api/post.ts
  client/components/molecules/dropdownInput/DropdownInput.tsx
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/sharingListItem/sharingListItemType.ts
  client/components/organisms/kakaoMap/KakaoMap.tsx
  client/components/organisms/nearByList/NearByList.tsx
  client/components/organisms/tab/nearByPageTab/NearByPageTab.tsx
  client/hooks/addNewHooks/useInput.ts
  client/hooks/addNewHooks/useInputType.ts
  client/hooks/search/useSearch.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/addnew/index.tsx
  client/pages/login/index.tsx
  client/pages/nearby/index.tsx
  client/pages/search/index.tsx
  client/yarn.lock
Labels: front

#218 Feat/back/google sub - 구글 로그인 구현
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
  server/src/main/java/com/main024/ngether/member/MemberService.java
Labels: back

#219 feat/back/chat - 하트비트 설정
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatService/AsyncService.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/config/ChatConfig.java
  server/src/main/java/com/main024/ngether/likes/Like.java
Labels: back

#220 feat/back/chat - 하트비트 헤더 추가
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
Labels: back

#221 feat/back/chat - 헤더추가
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
Labels: back

#223 feat/front/chat - 채팅 읽은 사람 수 실시간 렌더링
  client/components/organisms/chatGroup/ChatGroup.tsx
  client/components/organisms/chatRow/ChatRow.tsx
  client/components/organisms/chatRow/chatRowType.ts
  client/hooks/useWebSocketClient.ts
  client/pages/chatroom/[roomId].tsx
Labels: front

#224 Feat/front/googleLogin 소셜 로그인
  client/api/detail.ts
  client/api/login.ts
  client/api/members.ts
  client/components/container/defalutLayout/DefaultLayout.tsx
  client/components/container/layoutWithFooter/LayoutWithFooter.tsx
  client/components/molecules/detailBottom/DetailBottom.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/headers/mainHeader/mainHeader.ts
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/hooks/common/useLogin.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/api/auth/[...nextauth].ts
  client/pages/edit/[id].tsx
  client/pages/login/index.tsx
  client/pages/nearby/[id].tsx
  client/public/login/btn_google.png
  client/yarn.lock
Labels: front

#229 Feat/back/google - 소셜 로그인 구현
  server/build.gradle
  server/src/main/java/com/main024/ngether/auth/dto/OauthAttributes.java
  server/src/main/java/com/main024/ngether/auth/dto/SessionMemberDto.java
  server/src/main/java/com/main024/ngether/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/main024/ngether/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/main024/ngether/auth/handler/Oauth2MemberSuccessHandler.java
  server/src/main/java/com/main024/ngether/auth/utils/CustomOauth2UserService.java
  server/src/main/java/com/main024/ngether/auth/utils/ErrorResponder.java
  server/src/main/java/com/main024/ngether/config/QuerydslConfiguration.java
  server/src/main/java/com/main024/ngether/config/SecurityConfiguration.java
  server/src/main/java/com/main024/ngether/member/Member.java
  server/src/main/java/com/main024/ngether/member/MemberService.java
  server/src/main/java/com/main024/ngether/oauth2/HelloHomeController.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/hello-oauth2.html
Labels: back

#230 feat/front/addnew process - 글쓰기 후 리턴 boardId로 채팅방 생성
  client/pages/addnew/index.tsx
Labels: front

#231 feat/front/fix_type_song - 배포를 위한 함수 타입 지정
  client/api/detail.ts
  client/api/kakaoMap.ts
  client/api/members.ts
  client/api/post.ts
  client/pages/chatroom/index.tsx
  client/pages/login/index.tsx
  client/pages/nearby/index.tsx
Labels: front

#232 Feat/front/fix type khj
  client/components/container/layoutWithFooter/LayoutWithFooter.tsx
  client/components/container/loginChecker/loginCheckerType.ts
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/organisms/bottomNav/BottomNav.tsx
  client/components/organisms/chatRow/chatRowType.ts
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/headers/mainHeader/mainHeader.ts
  client/components/organisms/headers/mainHeader/mainHeaderType.ts
  client/components/organisms/nearByList/NearByList.tsx
  client/components/organisms/questionForm/QuestionForm.tsx
  client/components/organisms/questionList/QuestionList.tsx
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/components/organisms/tab/detailPageTab/detailPageTab.ts
  client/components/organisms/tab/mySharingTab/MySharingTab.tsx
  client/components/organisms/tab/nearByPageTab/NearByPageTab.tsx
  client/components/organisms/tabPanel/myPage/UserInquiry.tsx
  client/pages/addnew/index.tsx
  client/pages/nearby/index.tsx
Labels: front

#233 Feat/front/fix_type_kyunghyun
  client/api/kakaoMap.ts
  client/api/location.ts
  client/api/mySharing.ts
  client/components/atoms/input/inputType.ts
  client/components/molecules/detailBottom/DetailBottom.tsx
  client/components/molecules/detailBottom/detailBottomType.ts
  client/components/molecules/postMeta/PostMeta.tsx
  client/components/molecules/postMeta/postMetaType.ts
  client/components/molecules/sharingListItem/sharingListItemType.ts
  client/components/molecules/spot/SmallSpot.tsx
  client/components/molecules/spot/Spot.tsx
  client/components/molecules/spot/spot.ts
  client/components/molecules/spot/spotType.ts
  client/components/molecules/userMetaInfo/UserMetaInfo.tsx
  client/components/molecules/userMetaInfo/userMetaInfoType.ts
  client/hooks/addNewHooks/useInputType.ts
  client/pages/addnew/index.tsx
  client/pages/api/auth/[...nextauth].ts
  client/pages/chat/index.tsx
  client/pages/edit/[id].tsx
  client/pages/search/index.tsx
  server/build/resources/main/application.yml
  server/src/main/java/com/main024/ngether/auth/handler/Oauth2MemberSuccessHandler.java
  server/src/main/java/com/main024/ngether/chat/chatService/AsyncService.java
  server/src/main/java/com/main024/ngether/config/WebConfig.java
Labels: front

#234 Feat/front/fix_type
  client/api/detail.ts
  client/api/kakaoMap.ts
  client/api/location.ts
  client/api/members.ts
  client/api/mySharing.ts
  client/api/post.ts
  client/components/atoms/input/inputType.ts
  client/components/container/chatRoomLayout/ChatRoomLayout.tsx
  client/components/container/defalutLayout/DefaultLayout.tsx
  client/components/container/defalutLayout/defaultLayoutType.ts
  client/components/container/layoutWithFooter/LayoutWithFooter.tsx
  client/components/container/loginChecker/loginCheckerType.ts
  client/components/molecules/detailBottom/DetailBottom.tsx
  client/components/molecules/detailBottom/detailBottomType.ts
  client/components/molecules/dropdownInput/dropDownInputType.ts
  client/components/molecules/postMeta/PostMeta.tsx
  client/components/molecules/postMeta/postMetaType.ts
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/sharingListItem/sharingListItemType.ts
  client/components/molecules/spot/SmallSpot.tsx
  client/components/molecules/spot/Spot.tsx
  client/components/molecules/spot/spot.ts
  client/components/molecules/spot/spotType.ts
  client/components/molecules/userMetaInfo/UserMetaInfo.tsx
  client/components/molecules/userMetaInfo/userMetaInfoType.ts
  client/components/organisms/bottomNav/BottomNav.tsx
  client/components/organisms/chatRow/chatRowType.ts
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/headers/mainHeader/mainHeader.ts
  client/components/organisms/headers/mainHeader/mainHeaderType.ts
  client/components/organisms/nearByList/NearByList.tsx
  client/components/organisms/questionForm/QuestionForm.tsx
  client/components/organisms/questionList/QuestionList.tsx
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/components/organisms/tab/detailPageTab/detailPageTab.ts
  client/components/organisms/tab/mySharingTab/MySharingTab.tsx
  client/components/organisms/tab/nearByPageTab/NearByPageTab.tsx
  client/components/organisms/tabPanel/myPage/UserInquiry.tsx
  client/hooks/addNewHooks/useInput.ts
  client/hooks/addNewHooks/useInputType.ts
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/addnew/index.tsx
  client/pages/api/auth/[...nextauth].ts
  client/pages/chat/index.tsx
  client/pages/chatroom/index.tsx
  client/pages/edit/[id].tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/nearby/index.tsx
  client/pages/search/index.tsx
Labels: front

#238 dev - 비밀번호 오류 수정 후 재배포
  client/components/molecules/passwordTextField/TextField.tsx
  client/pages/login/index.tsx
Labels: front

#239 feat/front/edit_addNew_for_build - axios 수정
  client/pages/addnew/index.tsx
Labels: front

#241 dev - axios 수정 및 이미지 크롤러 url 수정
  client/pages/addnew/index.tsx
Labels: front

#242 feat/front/edit_addNew_for_build - API 수정으로 인한 axios method 변경
  client/pages/addnew/index.tsx
Labels: front

#243 dev - axios 수정
  client/pages/addnew/index.tsx
Labels: front

#244 feat/front/chat - 스크롤 이벤트 개선
  client/hooks/useWebSocketClient.ts
  client/pages/chatroom/[roomId].tsx
Labels: front

#245 dev - scroll event 개선
  client/hooks/useWebSocketClient.ts
  client/pages/chatroom/[roomId].tsx
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
Labels: front

#246 feat/front/chat - 스크롤 이벤트 조정 및 접근 권한있는 유저만 채팅방 접근 가능하도록 수정
  client/components/atoms/fobiddenMessage/ForbiddenMessage.tsx
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/hooks/useWebSocketClient.ts
  client/pages/chatroom/[roomId].tsx
Labels: front

#247 dev - 채팅 부분 수정
  client/components/atoms/fobiddenMessage/ForbiddenMessage.tsx
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/hooks/useWebSocketClient.ts
  client/pages/chatroom/[roomId].tsx
  server/src/main/java/com/main024/ngether/board/BoardController.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatService/AsyncConfig.java
  server/src/main/java/com/main024/ngether/chat/chatService/AsyncService.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/resources/application.yml
Labels: front

#248 feat/front/admin - 어드민 UI 및 채팅방 로직 수정
  client/components/container/adminLayout/AdminLayout.tsx
  client/components/molecules/reportDetail/reportBoardDetail/ReportBoardDetail.tsx
  client/components/molecules/reportDetail/reportBoardDetail/reportBoardDetail.ts
  client/components/molecules/reportDetail/reportChatDetail/ReportChatDetail.tsx
  client/components/molecules/reportDetail/reportChatDetail/reportChatDetail.ts
  client/components/organisms/chatItem/ChatItem.tsx
  client/components/organisms/chatItem/chatItemType.ts
  client/components/organisms/tab/adminTab/AdminTab.tsx
  client/components/organisms/tabPanel/admin/ReportWork.tsx
  client/hooks/useWebSocketClient.ts
  client/pages/addnew/index.tsx
  client/pages/admin/index.tsx
  client/pages/chatlist/index.tsx
Labels: front

#251 front/build_error_fix - type error 및 참조 오류 수정
  client/components/container/adminLayout/AdminLayout.tsx
  client/components/molecules/chatNoticeRow/ChatNoticeRow.tsx
  client/components/molecules/chatNoticeRow/chatNoticeRowType.ts
  client/components/molecules/reportDetail/reportBoardDetail/ReportBoardDetail.tsx
  client/components/molecules/reportDetail/reportBoardDetail/reportBoardDetailType.ts
  client/components/molecules/reportDetail/reportChatDetail/ReportChatDetail.tsx
  client/components/molecules/reportDetail/reportChatDetail/reportChatDetailType.ts
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/components/organisms/tab/detailPageTab/detailPageTabType.ts
  client/pages/addnew/index.tsx
Labels: front

#252 Feat/front/sort posts - 게시물 정렬, km별 요청, 내주변 목록 직접 접근
  client/api/kakaoMap.ts
  client/api/post.ts
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/toggleButtonGroup/ToggleButtonGroup.tsx
  client/components/molecules/toggleButtonGroup/toggleButtonGroupType.ts
  client/pages/nearby/index.tsx
Labels: front

#253 dev - 타입오류 및 참조오류 수정, 지도 기능 개선
  client/api/kakaoMap.ts
  client/api/post.ts
  client/components/container/adminLayout/AdminLayout.tsx
  client/components/molecules/chatNoticeRow/ChatNoticeRow.tsx
  client/components/molecules/chatNoticeRow/chatNoticeRowType.ts
  client/components/molecules/reportDetail/reportBoardDetail/ReportBoardDetail.tsx
  client/components/molecules/reportDetail/reportBoardDetail/reportBoardDetailType.ts
  client/components/molecules/reportDetail/reportChatDetail/ReportChatDetail.tsx
  client/components/molecules/reportDetail/reportChatDetail/reportChatDetailType.ts
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/toggleButtonGroup/ToggleButtonGroup.tsx
  client/components/molecules/toggleButtonGroup/toggleButtonGroupType.ts
  client/components/organisms/tab/detailPageTab/DetailPageTab.tsx
  client/components/organisms/tab/detailPageTab/detailPageTabType.ts
  client/pages/addnew/index.tsx
  client/pages/nearby/index.tsx
Labels: front

#254 feat/front/build_error_fix - mutate 부분 수정
  client/pages/addnew/index.tsx
Labels: front

#255 dev - mutate 수정
  client/pages/addnew/index.tsx
Labels: front

#256 Feat/back/oauth2 - 소셜 로그인 에러 수정
  server/build.gradle
  server/src/main/java/com/main024/ngether/auth/handler/Oauth2MemberSuccessHandler.java
  server/src/main/java/com/main024/ngether/auth/utils/CustomOauth2UserService.java
Labels: back

#257 feat/front/build_error_fix - 채팅 예외처리 타이밍 수정
  client/hooks/useWebSocketClient.ts
  client/pages/chatroom/[roomId].tsx
Labels: front

#258 dev - 채팅 예외처리 수정
  client/hooks/useWebSocketClient.ts
  client/pages/chatroom/[roomId].tsx
  server/build.gradle
  server/build/resources/main/application.yml
  server/src/main/java/com/main024/ngether/NgetherApplication.java
  server/src/main/java/com/main024/ngether/auth/handler/Oauth2MemberSuccessHandler.java
  server/src/main/java/com/main024/ngether/auth/utils/CustomOauth2UserService.java
  server/src/main/java/com/main024/ngether/chat/chatController/ChatRoomController.java
  server/src/main/java/com/main024/ngether/chat/chatService/AsyncConfig.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/config/QuerydslConfiguration.java
  server/src/main/java/com/main024/ngether/config/WebConfig.java
  server/src/main/java/com/main024/ngether/location/LocationMapper.java
  server/src/main/java/com/main024/ngether/location/LocationService.java
  server/src/main/java/com/main024/ngether/member/Member.java
  server/src/main/java/com/main024/ngether/member/MemberService.java
  server/src/main/java/com/main024/ngether/qna/qnaMapper/QnaMapper.java
  server/src/main/java/com/main024/ngether/qna/qnaService/QnaService.java
  server/src/main/resources/application.yml
Labels: front

#259 Feat/back/oauth2 - 소셜 로그인 api 구현
  server/src/main/java/com/main024/ngether/auth/handler/Oauth2MemberSuccessHandler.java
  server/src/main/java/com/main024/ngether/member/MemberController.java
  server/src/main/java/com/main024/ngether/member/MemberDto.java
  server/src/main/java/com/main024/ngether/member/MemberMapper.java
Labels: back

#263 Feat/back/refactor_jiyun - Board에 imageLink 필드 추가
  server/src/main/java/com/main024/ngether/board/Board.java
  server/src/main/java/com/main024/ngether/board/BoardDto.java
  server/src/main/java/com/main024/ngether/board/BoardMapper.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
Labels: back

#266 Feat/front/refactor_for_build - 로그인 / 로그아웃 수정
  client/components/container/adminLayout/AdminLayout.tsx
  client/components/container/defalutLayout/DefaultLayout.tsx
  client/components/container/layoutWithFooter/LayoutWithFooter.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/headers/mainHeader/mainHeaderType.ts
  client/pages/_app.tsx
  client/pages/api/auth/[...nextauth].ts
  client/pages/google/[id].tsx
  client/pages/google/index.tsx
  client/pages/login/index.tsx
Labels: front

#268 Feat/front/refactor_for_build
  client/components/container/adminLayout/AdminLayout.tsx
  client/components/container/defalutLayout/DefaultLayout.tsx
  client/components/container/layoutWithFooter/LayoutWithFooter.tsx
  client/components/organisms/headers/mainHeader/MainHeader.tsx
  client/components/organisms/headers/mainHeader/mainHeaderType.ts
  client/pages/_app.tsx
  client/pages/api/auth/[...nextauth].ts
  client/pages/google/[id].tsx
  client/pages/google/index.tsx
  client/pages/login/index.tsx
  server/src/main/java/com/main024/ngether/auth/handler/Oauth2MemberSuccessHandler.java
  server/src/main/java/com/main024/ngether/board/Board.java
  server/src/main/java/com/main024/ngether/board/BoardDto.java
  server/src/main/java/com/main024/ngether/board/BoardMapper.java
  server/src/main/java/com/main024/ngether/board/BoardService.java
  server/src/main/java/com/main024/ngether/chat/chatController/MessageController.java
  server/src/main/java/com/main024/ngether/chat/chatRepository/ChatMessageRepository.java
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
  server/src/main/java/com/main024/ngether/member/Member.java
  server/src/main/java/com/main024/ngether/member/MemberController.java
  server/src/main/java/com/main024/ngether/member/MemberDto.java
  server/src/main/java/com/main024/ngether/member/MemberMapper.java
Labels: front

#269 eat/front/chat - 웹소켓 연결 과정 리팩토링
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/hooks/useWebSocketClient.ts
  client/pages/chatroom/[roomId].tsx
Labels: front

#270 dev
  client/components/organisms/headers/chatHedaer/ChatHeader.tsx
  client/hooks/useWebSocketClient.ts
  client/pages/chatroom/[roomId].tsx
  server/src/main/java/com/main024/ngether/chat/chatService/ChatService.java
Labels: front

#272 Feat/back/qna - 질문 목록에 답변 리스트 추가
  server/src/main/java/com/main024/ngether/qna/qnaController/QnaController.java
  server/src/main/java/com/main024/ngether/qna/qnaMapper/QnaMapper.java
Labels: back

#271 Feat/front/addnew image - 게시글 등록 페이지 예외처리, helper text 출력, 이미지 크롤링
  client/components/atoms/input/inputType.ts
  client/components/molecules/dropdownInput/DropdownInput.tsx
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/sharingListItem/sharingListItemType.ts
  client/components/organisms/nearByList/NearByList.tsx
  client/hooks/addNewHooks/useInputType.ts
  client/package.json
  client/pages/addnew/index.tsx
  client/pages/nearby/index.tsx
  client/pages/search/index.tsx
  client/public/imageBox/base-box.svg
  client/utils/uploadPost/postInputValidation.ts
  client/yarn.lock
Labels: front

#273 dev
  client/components/atoms/input/inputType.ts
  client/components/molecules/dropdownInput/DropdownInput.tsx
  client/components/molecules/sharingListItem/SharingListItem.tsx
  client/components/molecules/sharingListItem/sharingListItemType.ts
  client/components/organisms/nearByList/NearByList.tsx
  client/hooks/addNewHooks/useInputType.ts
  client/package.json
  client/pages/addnew/index.tsx
  client/pages/nearby/index.tsx
  client/pages/search/index.tsx
  client/public/imageBox/base-box.svg
  client/utils/uploadPost/postInputValidation.ts
  client/yarn.lock
  server/src/main/java/com/main024/ngether/qna/qnaController/QnaController.java
  server/src/main/java/com/main024/ngether/qna/qnaMapper/QnaMapper.java
Labels: front

#275 Feat/front/refactor for build - google login form 추가
  client/api/members.ts
  client/pages/edit/[id].tsx
  client/pages/google/index.tsx
Labels: front

#274 fix - #260 카테고리 기본값 delivery로 들어가는거 수정
  client/pages/addnew/index.tsx
Labels: front

#276 dev
  client/api/members.ts
  client/pages/addnew/index.tsx
  client/pages/edit/[id].tsx
  client/pages/google/index.tsx
Labels: front

#277 Feat/back/qna- 닉네임 수정 기능 수정
  server/src/main/java/com/main024/ngether/auth/utils/CustomOauth2UserService.java
Labels: back

#278 Feat/front/refactor for build - 정지 이용자 로그인 메시지 추가
  client/components/organisms/bottomNav/BottomNav.tsx
  client/pages/login/index.tsx
Labels: front

#281 Feat/front/refactor_for_build
  client/components/organisms/bottomNav/BottomNav.tsx
  client/pages/login/index.tsx
Labels: front
